fixtures:
    symlinks:
        consul: "#{source_dir}"
    forge_modules:
        vcsrepo: puppetlabs/vcsrepo
        stdlib: puppetlabs/stdlib
        golang: scottyc/golang
        python: stankevich/python
    repositories:
        docker: https://github.com/scotty-c/garethr-docker.git
