#!/usr/bin/ruby env

require "socket"
$hostname = Socket.gethostname

forge 'http://forge.puppetlabs.com'

mod 'puppetlabs/stdlib', '4.12.0'
mod 'puppetlabs/apt', '2.2.2'
mod 'stahnma/epel'
mod 'garethr/docker', :git => "https://github.com/scotty-c/garethr-docker.git"
mod 'stankevich/python'

