#!/usr/bin/ruby env

require "socket"
$hostname = Socket.gethostname

forge 'http://forge.puppetlabs.com'

mod 'puppetlabs/stdlib', '4.12.0'
mod 'puppetlabs/apt', '2.2.2'
mod 'stahnma/epel', '1.2.2'
mod 'garethr/docker', '5.3.0'

